### ISSUE TITLE
loopback 4 vs loopback 3 vs nestjs

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#13]
loopback 4 doesn't support some data relations:
 https://github.com/loopbackio/loopback-next/issues/1920

and its getting complicated to do simple relations...

**Comment by watchoutfreedom** [comment]
so we keep in loopback 3?

**Comment by albjeremias** [comment]
loopback 4. si. por ahora todo bien! :)

**Comment by albjeremias** [comment]
we are now using nestjs
