### ISSUE TITLE
implement ci

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#16]
to run tests
later to push docker image?!

**Comment by albjeremias** [comment]
need help on implementing a ci.. running the command:

`$ npm run test`

**Comment by albjeremias** [comment]
I tried with travis: 

https://github.com/helpbuttons/hb-back/blob/develop/.travis.yml 

but the jobs won't start...

and with github workflow:
https://github.com/helpbuttons/hb-back/commit/bd59d6bb96f25ceeedb454b294525a8092171212
also nothing happened...

**Comment by watchoutfreedom** [comment]
Did it work before?
