### ISSUE TITLE
implement transfer button

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-back#20]
(It was like this, we can debate about it) A user can change his/her buttons ownership to other user. Just in the edit menu of the button they insert the username or email and change the creator. Even if the affected user isn't in the platform they receive an email.

**Comment by albjeremias** [comment]
@watchoutfreedom from what i understand there is only one owner per button? :D

**Comment by watchoutfreedom** [comment]
Yes just one owner, but we had the option to change the ownership, "transfer" to other people. For example in social cooperation is common to find a task and assign that to a person ( similar to github) . We were resolving this by transfering the button and notifying the user . This could be achieved also by adding roles to the button but for simplicity we just transfer them

**Comment by albjeremias** [comment]
it will be easily extensible to support many users... but for now it simplifies...

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/hb-back/pull/49/files
