### ISSUE TITLE
Think an implement HB platform and HOST services

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-back#22]
Think about a potential strategy to sustain the project in the long term by building community and designing a tier system to offer services / receive donations by the core team.

**Comment by albjeremias** [comment]
@watchoutfreedom i closed this issue, i dont think that its related to the backend!

**Comment by watchoutfreedom** [comment]
Ok. Just mentioned cause it would be related to the services you mentioned that could be offered by the platform
