### ISSUE TITLE
implement map view

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-back#23]
Networks have enum property showButtons for default display setup. It can be:
- map showing exact location buttons, 
- map showing exact location buttons + list, 
- map showing areas (honeycomb model) +list
- just list by areas (honeycomb logic of buttons by areas but without the map), 

we need to think how's the best way to implement this  regarding the backend and alternatives

honecomb repo by @hirunatan :

https://github.com/Adriamelendo/Honeycomb-Map/tree/master/frontend

**Comment by albjeremias** [comment]
I'm a bit confused about this issue. is this issue more related to the frontend maybe? which api endpoints do you need for this?

>
>    map showing exact location buttons,
api/buttons/find
?radius=10km&center[3.45343,13.53534]

>    map showing exact location buttons + list,
```
{
  "where": {
    "area": {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  1.71112060546875,
                  41.24993502644133
                ],
                [
                  2.4211120605468746,
                  41.24993502644133
                ],
                [
                  2.4211120605468746,
                  41.544561218705965
                ],
                [
                  1.71112060546875,
                  41.544561218705965
                ],
                [
                  1.71112060546875,
                  41.24993502644133
                ]
              ]
            ]
          }
        }
      ]
    }
  }
}
```

>    map showing areas (honeycomb model) +list
>    just list by areas (honeycomb logic of buttons by areas but without the map),

**Comment by albjeremias** [comment]
Using geoJson with leaflet:
https://leafletjs.com/examples/geojson/

postgis dealing with geoJson:
https://postgis.net/docs/ST_GeomFromGeoJSON.html

Exists a stackoverflow only about gis:
https://gis.stackexchange.com/

other documentation.. keep on adding to this issue
https://www.postgresonline.com/journal/archives/267-Creating-GeoJSON-Feature-Collections-with-JSON-and-PostGIS-functions.html

**Comment by watchoutfreedom** [comment]
thank you I will take a look

**Comment by watchoutfreedom** [comment]
Definetly is more related to the front but I wanted you to know how we want to use the data so you can think about the best way to store - answer to this :)

**Comment by albjeremias** [comment]
> Definetly is more related to the front but I wanted you to know how we want to use the data so you can think about the best way to store - answer to this :)

I want to store using geojson! what do you think? leaflet supports it directly with polygons, ways etc...

**Comment by watchoutfreedom** [comment]
It looks like geojson generally stores coordinates together, I suppose it's something that can be customized to adapt to what we do (separate longitude and latitude ) or how is going to be the flow between the two ways to change between two ways ? I think geojson is great option for the rest of what I see

**Comment by albjeremias** [comment]
> It looks like geojson generally stores coordinates together, I suppose it's something that can be customized to adapt to what we do (separate longitude and latitude ) or how is going to be the flow between the two ways to change ? I think geojson is great option for the rest of what I see

geojson will be what the api will answer back... you can easily draw it with leaflet!! Will you use leaflet?
https://leafletjs.com/examples/geojson/
@watchoutfreedom

**Comment by watchoutfreedom** [comment]
yes we use leaflet, thank you

**Comment by albjeremias** [comment]
implemented in:
https://github.com/helpbuttons/hb-back/pull/30
https://github.com/helpbuttons/hb-back/pull/28
https://github.com/helpbuttons/hb-back/pull/27
