### ISSUE TITLE
implement date/recurring dates of a template button

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#29]
- can be a normal date
 -  an array of dates
 - a recurrent date (https://momentjs.com/docs/#/plugins/recur/)

@watchoutfreedom can we make up some examples? maybe with momentjs.. i will try if you can't

**Comment by albjeremias** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/26681446/133311167-bb58ece6-9dc8-4afd-ac1e-7e311ab540cb.png">

**Comment by watchoutfreedom** [comment]
I'm fine with momentjs , just should I add it in the front and make it print??

**Comment by watchoutfreedom** [comment]
Main Examples would be (they can be customized by templates also):   
- Ahora (siempre)
- Lunes, 23 de Julio de 2021
- De Lunes 23 de Julio a Martes 22 de Agosto de 2021
- De Lunes 23 de Julio a Martes 22 de Agosto de 2021
- Martes, miércoles y viernes a las 16:00
- El primer lunes de cada mes

**Comment by albjeremias** [comment]
@watchoutfreedom 
ill continue with the geojson, but if you want you can read the documentation in here:
https://github.com/c-trimm/moment-recur#creating-a-recurring-date 
and try it out! ;)

**Comment by watchoutfreedom** [comment]
okk thankss

**Comment by albjeremias** [comment]
I think this is solved on the frontend...

https://github.com/c-trimm/moment-recur#utility-methods

you have here the
`recurrence.save();`

which generates a object that we can store on the database on the buttontemplate values!
closing.
