### ISSUE TITLE
Chore: Dependencias incompletas 

### ISSUE THREAD

**Issue by dbrab** [helpbuttons/hb-back#79]
Hola ,por lo que he observado algunas dependencias estan incompletas, por ejemplo faltan los types de mocha , usan una característica llamada 'useUnknownInCatchVariables'.  , la cual solo esta disponible en typescript 4.4 hacia adelante, pero el package.json solo tiene la ~4.3.4 , esto nunca obtendrá la 4.4.x  , no esta definido bcryptjs .

**Comment by watchoutfreedom** [comment]
Entonces deberíamos actualizar el json a typescript 4.4?

**Comment by watchoutfreedom** [comment]
Si puedes actualizarlo y lo probamos ?
