### ISSUE TITLE
implement tag system

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#8]
different approaches in here:
http://howto.philippkeller.com/2005/04/24/Tags-Database-schemas/

i was more thinking of a microservice which only handles this issue... but might be too complex. need to research further.

**Comment by watchoutfreedom** [comment]
This part of the app is one of the most important, specially in middle term. So for me it makes sense to have its own microservice   even if it's complex. Also think about the relation between buttons --- nets ---- tags -- interests -- users :) -->

![image](https://user-images.githubusercontent.com/23015314/132895371-59d239d6-313f-4457-bf05-ab23c69475f4.png)

**Comment by albjeremias** [comment]
i was now thinking that the best would be to have redundancy.. and dont create any relations between the "models" and the tags table...
so everytime u add a new tag to any "model" that supports tags, it would add a copy of the value in the "model" table.. and a copy with the model name, model id, and the tag... so if we need to get all tags for all models, we run a very efficient query. 

the question is.. how will the tags look like in the ui? which will be the most used queries? we can optimize it based on that.

**Comment by watchoutfreedom** [comment]
tags appear on the button-file, either on the map or on the list or on the page. Also appear on the user profile and on the user edition when adding interests (interest is a different model that's associated with a tag, I guess it's what you're saying) . Networks can also defined important tags that later are used for suggestions or preferred filtering the content.

**Comment by albjeremias** [comment]
tags:
 - button
   -> `SELECT UNIQUE(id) FROM tag WHERE modelName = 'button'`

 - user profile
   -> `SELECT UNIQUE(id) FROM tag WHERE modelName = 'user'`
   
 - networks
   -> `SELECT UNIQUE(id) FROM tag WHERE modelName = 'network'`

all:
   -> `SELECT UNIQUE(id),count(id) FROM tag

**Comment by watchoutfreedom** [comment]
ok, interests in theory is related to a tag and also has an type and a specific list of nets, is a more complex tag. So I guess we can take the relation with the tag , and like this ? : 

-> SELECT UNIQUE(id) FROM interest WHERE id = 'tag'

**Comment by albjeremias** [comment]
> ok, interests in theory is related to a tag and also has an type and a specific list of nets, is a more complex tag. So I guess we can take the relation with the tag , and like this ? :
> 
> -> SELECT UNIQUE(id) FROM interest WHERE id = 'tag'
> 
> Interest have also an user related to it @albjeremias

i dont think you understood my proposal. but tell me what do you want? all interests of a user?
`SELECT UNIQUE(id) FROM tag WHERE modelName = 'user' AND modelId = 'userId';`

**Comment by watchoutfreedom** [comment]
@albjeremias yes , I was going to tell you that I don't get it XD. Basically an interest is stored model that allows the user to specify if they want to receive alerts for specific tags, button types or networks

**Comment by albjeremias** [comment]
dont worry.. you will just have to call:
 - /users/findById/{id}
This endpoint is not yet implemented.. because im having some trouble with authentication and extending the proprieties of the User. created issue: #36 

and get all the tags or:
 - /tags/findByTag/{tag}
This endpoint is already up and running

**Comment by watchoutfreedom** [comment]
It's not well styled any more but yoou can see how for each tag one user can select from which nets wants to receive alerts and for wihich types (need / offer , the two ovals on the right) can receive those alerts

<img width="888" alt="Captura de pantalla 2021-09-17 a las 19 38 09" src="https://user-images.githubusercontent.com/23015314/133830793-f0d976e2-8db7-4239-9033-1a3e84201b02.png">
