### ISSUE TITLE
implement user model and authentication & authorization

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-back#9]
https://loopback.io/doc/en/lb4/Authentication-overview.html

**Comment by albjeremias** [comment]
@watchoutfreedom where can i see the user model? :) got somewhere lost in the long chat history we have

**Comment by watchoutfreedom** [comment]
hey no prob, User model and the dependant models can be seen here :
https://dbdiagram.io/d/61275bb76dc2bb6073bc5755

**Comment by watchoutfreedom** [comment]
<img width="600" alt="Captura de pantalla 2021-09-10 a las 22 34 59" src="https://user-images.githubusercontent.com/23015314/132907820-8f3e4a3a-846c-4441-86ed-359c0ea66421.png">

**Comment by albjeremias** [comment]
@watchoutfreedom ill proceed with this next.. since you requested it on the #4  ;)

**Comment by watchoutfreedom** [comment]
Yes let's make an issue with the more complex and make the simpler for now
